syntax on
set relativenumber 
set visualbell
set encoding=utf-8
set backspace=indent,eol,start
set autoindent
set tabstop=4
set smartindent
set shiftwidth=4
set expandtab

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'Valloric/YouCompleteMe'

call plug#end()
